name: MyTelevision
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.1.8+11

environment:
  sdk: ">=3.9.0 <4.4.0"
  flutter: 3.35.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: 4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.1
  permission_handler: ^12.0.1
  flutter_svg: ^2.0.10
  get_storage: ^2.1.1
  pin_code_fields: 8.0.1
  #  flutter_gen: ^5.7.0
  #  path_provider:
  carousel_slider: ^5.1.1
  #  fl_chart:
  #  flutter_glow: ^0.3.2
  image_picker: ^1.2.0
  flutter_animate: ^4.5.2
  video_player: ^2.10.0
  chewie: 1.12.1
  device_info_plus: 11.5.0
  share_plus: 11.1.0
  r_dotted_line_border: ^0.1.1
  iconsax: ^0.0.8
  logger: 2.6.1
  flutter_spinkit: ^5.2.2
  intl: 0.20.2
  rename_app: ^1.6.5
  youtube_player_flutter: ^9.1.2
  restart_app: ^1.3.2
  google_mobile_ads: ^6.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  wakelock_plus: ^1.2.1
  flutter_to_airplay: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
#  build_runner:
#  flutter_gen_runner:
#  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app/ios_launcher.jpg"
  image_path_ios: "assets/app/ios_launcher.jpg"

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true

  assets:
    - assets/app/app_launcher.png
    - assets/app/basic_logo_for_dark.png
    - assets/app/basic_logo_for_light.png
    - assets/app/ios_launcher.jpg
    - assets/bg/congratulations.svg
    - assets/bg/container.png
    - assets/bg/dashboard_bg.svg
    - assets/bg/dashboard_item_bg.png
    - assets/icons/demography.svg
    - assets/icons/home.svg
    - assets/icons/mystery.svg
    - assets/icons/notifications.svg
    - assets/icons/person.svg
    - assets/logo/account_circle.png
    - assets/logo/account_circle.svg
    - assets/logo/app_launcher.png
    - assets/logo/app_logo.png
    - assets/logo/app_logo.svg
    - assets/logo/logo.png
    - assets/logo/logo.svg
    - assets/data/default_languages.json
